# PRACTICE SET
'''
1. Write a python program to Add two number.
2. write a program to find remainder when a number is divide by Z.
3. check the type of variable assigned using input () function.
4. Use comparison operator to find out whether a given variable a is greater then 'b' or not. take a=34 and b=80.
5. write a python program find an average of two numbers entered by the user.
6. write a Python program to Calculate the square the square of number entered by this user.
'''

# Solution 1

x = int(input("Enter the firrst number: "))
y = int(input("Enter the second Number: "))

Result = x + y
print("The sum of the two Number Is: ", Result)

# Solution 2
